# Generated by Django 2.2.1 on 2019-05-22 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyMove',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('kakao_id', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('possible_time', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Move')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplyCare',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('kakao_id', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('possible_month', models.IntegerField()),
                ('current_location', models.CharField(max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Care')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplyAdoption',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('kakao_id', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('current_location', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Adoption')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
