# Generated by Django 2.2.1 on 2019-05-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='media/test.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.Post')),
                ('sex', models.CharField(max_length=2)),
            ],
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.Post')),
                ('current_location', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=2)),
            ],
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.Post')),
            ],
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.Post')),
                ('sex', models.CharField(max_length=2)),
                ('pet_name', models.CharField(max_length=20)),
            ],
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.Post')),
                ('current_location', models.CharField(max_length=40)),
                ('destination_location', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=2)),
            ],
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.Post')),
                ('current_location', models.CharField(max_length=40)),
            ],
            bases=('post.post',),
        ),
    ]
