# Generated by Django 2.2.1 on 2019-05-22 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='media/test.png', null=True, upload_to='')),
                ('current_location', models.CharField(max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='media/test.png', null=True, upload_to='')),
                ('current_location', models.CharField(max_length=40)),
                ('destination_location', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='media/test.png', null=True, upload_to='')),
                ('sex', models.CharField(max_length=2)),
                ('pet_name', models.CharField(max_length=20)),
                ('type', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='media/test.png', null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='media/test.png', null=True, upload_to='')),
                ('current_location', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='media/test.png', null=True, upload_to='')),
                ('sex', models.CharField(max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
