# Generated by Django 2.2.1 on 2019-06-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find',
            name='type',
        ),
        migrations.AddField(
            model_name='adoption',
            name='age',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='adoption',
            name='kind',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='care',
            name='age',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='care',
            name='kind',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='find',
            name='kind',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='kind',
            field=models.TextField(default=0),
        ),
    ]
